### ISSUE TITLE
Issue with using the curate_data branch main.py

### ISSUE THREAD

**Issue by tangjjbetsy** [huispaty/batik_plays_mozart#5]
Hi, I got the following issues when running `python ./main.py` after installing the environment:

```
Aligning score parts to performances and annotations
 22%|██████████████████▋                                                                 | 8/36 [00:52<03:03,  6.56s/it]
Traceback (most recent call last):
  File "/data/scratch/USER/batik_plays_mozart/./main.py", line 113, in <module>
    prepare_new_match.create_matchfile(piece, score2score_dir, perf2score_dir, align_old_dir, score_dir, performance_midi_dir)
  File "/data/scratch/USER/batik_plays_mozart/utils/prepare_new_match.py", line 233, in create_matchfile
    new_match_file = pt.io.exportmatch.matchfile_from_alignment(new_perf2score_alignment, match_ppart, score_part, performer=performer, composer=composer, piece=piece_info, score_filename=score_fn, performance_filename=performance_fn, assume_part_unfolded=True, tempo_indication=score.movement_title, diff_score_version_notes=diff_score_version_notes)
  File "/data/home/USER/.conda/envs/batik_plays_mozart/lib/python3.9/site-packages/partitura/utils/misc.py", line 90, in wrapper
    return f(*args, **kwargs)
  File "/data/home/USER/.conda/envs/batik_plays_mozart/lib/python3.9/site-packages/partitura/io/exportmatch.py", line 420, in matchfile_from_alignment
    duplicate_idx = np.concatenate(np.array(list(duplicates.values()))).flatten()
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (15,) + inhomogeneous part.
```
Do you have any idea of why this happened?

Specifically, it happened to `piece 281_3` when creating the new match.

**Comment by huispaty** [comment]
Hello! Thank you for pointing out this issue - it's related to the numpy version 1.26 and partitura. 

Please temporarily replace the line throwing the error in the partitura install in your environment:
`duplicate_idx = np.concatenate(np.array(list(duplicates.values()))).flatten()` 
to:
`duplicate_idx = np.hstack(list(duplicates.values()))`

Meanwhile I'll add the fix in the partitura package itself, so it'll be in the next release. Thank you again for pointing it out:)

**Comment by huispaty** [comment]
partitura + numpy version>1.21 incompatibility issue, changed line in partitura package
